# Natural Language Processing

## Importing Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv("SMS_mail.csv",encoding= 'unicode_escape')

In [3]:
dataset.head()

S. No.                                       Message_body     Label
0       1                         Rofl. Its true to its name  Non-Spam
1       2  The guy did some bitching but I acted like i'd...  Non-Spam
2       3  Pity, * was in mood for that. So...any other s...  Non-Spam
3       4               Will ü b going to esplanade fr home?  Non-Spam
4       5  This is the 2nd time we have tried 2 contact u...      Spam

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 957 entries, 0 to 956
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   S. No.        957 non-null    int64 
 1   Message_body  957 non-null    object
 2   Label         957 non-null    object
dtypes: int64(1), object(2)
memory usage: 22.6+ KB


In [5]:
dataset.isnull().sum()

S. No.          0
Message_body    0
Label           0
dtype: int64

In [6]:
dataset["Label"]=dataset["Label"].map({'Non-Spam':0,'Spam':1})

In [7]:
dataset

S. No.                                       Message_body  Label
0         1                         Rofl. Its true to its name      0
1         2  The guy did some bitching but I acted like i'd...      0
2         3  Pity, * was in mood for that. So...any other s...      0
3         4               Will ü b going to esplanade fr home?      0
4         5  This is the 2nd time we have tried 2 contact u...      1
..      ...                                                ...    ...
952     953  hows my favourite person today? r u workin har...      0
953     954                      How much you got for cleaning      0
954     955  Sorry da. I gone mad so many pending works wha...      0
955     956                                 Wat time ü finish?      0
956     957                    Just glad to be talking to you.      0

[957 rows x 3 columns]

In [15]:
import nltk
nltk.download('stopwords')

[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [25]:
import re  # re is regular expression use to replace values
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus=[]
for i in range(0,957):
    m_body=re.sub('[^a-zA-Z]',' ',dataset["Message_body"][i])    #sub is use for substitution it give only alphabets a to z and A to Z
    m_body=m_body.lower()
    m_body=m_body.split()   # it will split all reviews
    ps=PorterStemmer()
    all_stopwords=stopwords.words("english")
    all_stopwords.remove
    m_body=[ps.stem(word)for word in m_body if not word in set(all_stopwords)]  #this process is use for remove stop words from list
    m_body=' '.join(m_body)
    corpus.append(m_body)

In [26]:
print(corpus)

['rofl true name', 'guy bitch act like interest buy someth els next week gave us free', 'piti mood suggest', 'b go esplanad fr home', 'nd time tri contact u u pound prize claim easi call p per minut bt nation rate', 'remind get pound free call credit detail great offer pl repli text valid name hous postcod', 'huh lei', 'wait til least wednesday see get', 'ard like dat lor', 'ok lor soni ericsson salesman ask shuhui say quit gd use consid', 'get dump heap mom decid come low bore', 'anyth lor juz us lor', 'next lt gt hour imma flip shit', 'sorri call later', 'meant calcul lt gt unit lt gt school realli expens start practic accent import decid year dental school nmde exam', 'ye u text pshew miss much', 'yeh indian nice tho kane bit shud go drink sometim soon mite hav go da work laugh soon love pete x x', 'well keep mind got enough ga one round trip bar sudden influx cash', 'hahaha use brain dear', 'safe trip nigeria wish happi soon compani share moment', 'wen get spiritu deep great', 'coo

## Creating the Bag of Words model

In [27]:
from sklearn.feature_extraction.text import CountVectorizer #convert text doc into matrix to token count
cv=CountVectorizer(max_features=1200 )
X=cv.fit_transform(corpus).toarray()
y=dataset.iloc[:,-1].values

In [28]:
y

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,

## Splitting the dataset into the Training set and Test set

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

## Training the Naive Bayes model on the Training set

In [31]:
from sklearn.naive_bayes import GaussianNB  # it did training on the basis of historical data
clasifier=GaussianNB()
clasifier.fit(X_train,y_train)

GaussianNB()

## Predicting the Test set results

In [34]:
y_pred=clasifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 1]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]

## Making the Confusion Matrix

In [42]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[150  12]
 [ 11  19]]


In [46]:
accuracy=accuracy_score(y_test,y_pred)
print("accuracy is:",accuracy)

accuracy is: 0.8802083333333334


In [45]:
accuracy

0.8802083333333334